config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  post 'posts', to: 'posts#create'
  get  'posts', to: 'posts#new'
  
  
  get 'posts/:id', to: 'posts#show'
  
  get 'signup', to: 'users#new' 
    resources :users, only: [:index, :show, :new, :create]do
     member do
        get :favorites
      end
    end
    
  get 'search', to: 'posts#search'
  
  resources :posts, only: [:create, :edit, :update, :destroy] do
  resource :comments, only: [:create, :destroy]
  end 
  
  
  resources :posts, only: [:create, :edit, :update, :destroy]
  resources :favorites, only: [:create, :destroy]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :content, presence: true, length: { maximum: 255 }
    mount_uploader :img, ImgUploader
    validate :img_size
    
    has_many :favorites
    has_many :users, through: :favorites
    
    has_many :comments, dependent: :destroy
    
    def img_size
      if img.size > 5.megabytes
        errors.add(:img, "should be less than 5MB")
      end
    end
    
    def self.search(search)
      if search
        Post.where(['content LIKE ?', "%#{search}%"])
      else
        Post.none
      end
    end
   
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum:30 }
    validates :email, presence: true, length: { maximum:255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    
    has_secure_password
    
    has_many :posts
    
    has_many :favorites
    has_many :favorite_posts, through:  :favorites, source: :post, dependent: :destroy
    
    has_many :comments, dependent: :destroy
    def favorite(post)
      favorites.find_or_create_by(post_id: post.id)
    end
    
    def unfavorite(post)
      favorite = self.favorites.find_by(post_id: post.id)
      favorite.destroy if favorite
    end
  
    def favorite?(post)
      self.favorite_posts.include?(post)
    end

    def feed_posts
    @posts = Post.all
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  def counts(user)
    @count_posts = user.posts.count
    @count_favorites = user.favorites.count
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: post_url(@post))
    else
      flash[:danger] = "コメントできません"
      redirect_back(fallback_location: post_url(@post))
    end
  end 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to request.referer
  end


  private
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
     before_action :require_user_logged_in

def create
  @post = Post.find(params[:post_id])
  current_user.favorite(@post)
  flash[:success] = 'お気に入りにしました。'
end

  def destroy
    @post=Post.find(params[:post_id])
    current_user.unfavorite(@post)
    flash[:success] = 'お気に入りを外しました'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿しました。'
      redirect_to root_url
    else
      @posts = current_user.posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = '投稿に失敗しました。'
      render 'toppages/index'
    end
  end
  def new
    @post = Post.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
     @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = '更新しました。'
      redirect_to request.referer
    else
      flash[:danger] = '更新に失敗しました。'
      render :new
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = current_user.comments.new
  end
  
  def image
    @posts = Post.where(user_id: current_user.id).where.not(image: nil)
  end
  
  def url
    @posts = Post.where(user_id: current_user.id).where.not(url: nil)
  end
  
  def search
    @posts = Post.search(params[:keyword])
  end

  private

  def post_params
    params.require(:post).permit(:content, :img, :url)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
      @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(20)
  end

  def show
    @user = User.find(params[:id])
    
    @posts = @user.posts.order(id: :desc).page(params[:page])
    counts(@user)
    
    @posts.each do |post|
      @comments = post.comments
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  
  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorite_posts.page(params[:page])
    counts(@user)
  end
   private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  require "uri"

def text_url_to_link text

  URI.extract(text, ['http','https'] ).uniq.each do |url|
    sub_text = ""
    sub_text << "<a href=" << url << " target=\"_blank\">" << url << "</a>"

    text.gsub!(url, sub_text)
  end

  return text
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/favorites/_favorites_button.html.erb
<% if current_user.favorite?(post) %>
    <%= form_with(model: current_user.favorites.find_by(post_id: post.id), method: :delete) do |f| %>
      <%= hidden_field_tag :post_id, post.id %>
      <%= f.submit 'お気に入りを外す', class: 'btn btn-danger btn-sm' %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.favorites.build) do |f| %>
      <%= hidden_field_tag :post_id, post.id %>
      <%= f.submit 'お気に入り', class: 'btn btn-secondary btn-sm' %>
    <% end %>
  <% end %> 

app/views/favorites/create.js.erb
console.log('hello');
$("#favorite").html("<%=j (render(partial: 'favorites/favorites_button', locals:{ post: @post }))%>");

app/views/favorites/destroy.js.erb
console.log('hello');
$("#favorite").html("<%=j (render(partial: 'favorites/favorites_button', locals:{ post: @post }))%>");

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <a class="navbar-brand" href="/">OWN</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'search', search_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= render 'posts/new' %>
          </li>
          
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user), class: 'nav-link' %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>
          </li>
         <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>OWN</title>
    
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript">
    </script>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
    <%= render 'layouts/flash_messages' %>

    
    <%= yield %>
  </body>
</html>

app/views/posts/_new.html.erb
<%= content_tag :div, 'NewPost', class: 'nav-link', 'data-toggle': "modal", 'data-target': "#exampleModalLong", style: "cursor:pointer" %>

<!-- Modal -->
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">投稿</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
            <div class="col-sm-6 offset-sm-3">
              <div>
                <%= form_with(model: Post.new, url: posts_path, local: true) do |f| %>
                <div class="form_group">
                  <%= f.label :url, 'URL' %>
                  <p class='url'><%= f.url_field :url, class: 'form_contorol'%></p>
                </div>
                
                <div class="form-group">
                  <p class='text-post'><%= f.text_area :content, class: 'form-control'%></p>
                </div>
                <div>
                  <%= f.file_field :img, class: "image" %>
                  <p>※画像をアップロードする場合はこちらからファイルを選択してください</p>
                </div>
                <div class="text-center">
                  <%= f.submit '投稿する', class: 'btn btn-secondary rounded-pill' %>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<ul>
  <% posts.each do |post| %>
    <li class="media mb-3">
      <div class="media-body">
        <div>
          <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted">posted at <%= post.created_at %></span>
        </div>
        <div class="box">
          <p class="text"><%= link_to(post.content, "/posts/#{post.id}", data: {"turbolinks" => false}, class: 'link') %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>編集</h1>

<div class="col-sm-6 offset-sm-3">
  <div>
    <%= form_for @post do |f| %>
    <div class="form_group">
      <%= f.label :url, 'URL' %>
      <%= f.url_field :url, class: 'form_contorol', :size => "69" %>
    </div>
    
    <div class="form-group">
      <%= f.text_area :content, class: 'form-control', :size => "100x7"  %>
    </div>
    <div>
      <%= f.file_field :img, class: "image" %>
      <p>※画像をアップロードする場合はこちらからファイルを選択してください</p>
    </div>
    <div class="text-center">
      <%= f.submit '投稿する', class: 'btn btn-secondary rounded-pill' %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.js.erb
$('#post-modal').html('<%= j(render 'new') %>')
$('#post-modal').modal('show')

app/views/posts/search.html.erb
<div class='container'>
  <div class='row'>
    <%= form_with url: search_path, method: :get, local: true do |f| %>
    <div class='col-sm-7, search'>
    <p>キーワード</p>
      <div class='form'>
        <%= f.text_field :keyword %>
        <%= f.submit 'Search', :class=>"btn btn-secondary", :search => nil  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<ul>
  <% @posts.each do |post| %>
    <li class="media mb-3">
      <div class="media-body">
        <div>
          <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted">posted at <%= post.created_at %></span>
        </div>
        <div class="box">
          <p><%= image_tag (post.img.to_s),  :size => "288x162" if post.img? %></p>
          <p class="text"><%= link_to(post.content, "/posts/#{post.id}", class: 'link') %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<div class='container'> 
    <div class="content-box">
      <%= link_to (@post.img.to_s), "data-lightbox" => (@post.img.to_s) do %>
      <div class='image'><%= image_tag (@post.img.to_s), class: 'img' if @post.img? %></div>
      <% end %>
      <p class="text"><%= @post.content %></p>
    </div>
</div>   
  <div class="container mt-4">
    <div class='btn-group'>
      <div id='favorite'>
        <%= render 'favorites/favorites_button', post: @post %>
      </div>
      <%= link_to "アクセス", (h(@post.url)).html_safe, class: 'btn btn-primary btn-sm' %>
      <% if current_user == @post.user %>
        <%= link_to "削除", @post, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
        <%= link_to "編集", edit_post_path, class: 'btn btn-warning btn-sm' %>
      <% end %>
    </div>
  </div>
<div class='container'>
  <div class="comment">
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content, class: 'comment-form'%>
      <%= f.submit "コメントする", class: "btn btn-secondary rounded-pill" %>
    <% end %>
    </div>
  <h1>コメント一覧</h1>
  <div class="comment-content">
    <% @comments.each do |comment| %>
      <div>
        <strong><%= link_to comment.user.name,user_path(@post.user) %></strong>
        <br />
        <p class=""><%= comment.content %></p>
        <% end %>
      </div>
  </div>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
  <div class="col-sm-8">
    <%= render 'posts/posts', posts: @posts %>
  </div>
<% else %>

<div class="text-center">
  <h1 style="font-size: 35px;">あなたのオリジナルWebサイト、アプリ、サービスを投稿しよう‼</h1>
  <div class="btn">
    <%= link_to 'ログイン', login_path, class: 'btn btn-secondary w-150px ' %>
    <%= link_to 'ユーザー登録', signup_path, class: 'btn btn-secondary w-150px' %>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-sm-9'>
      <%= render 'posts/posts', posts: @posts%>
    </div>
  </div>
</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/favorites.html.erb
<div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">投稿一覧  <span class="badge badge-secondary"><%= @count_posts %></span></a></li></a></li>
      <li class="nav-item"><a href="<%= favorites_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(favorites_user_path(@user)) %>">お気に入り一覧  <span class="badge badge-secondary"><%=  @count_favorites %></span></a></li>
    </ul>
    <%= render 'posts/posts', posts: @favorites %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: @user, local: true) do|f| %>
    
    <div class="form-group">
      <%= f.label :name, 'ユーザー名' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password, 'パスワード' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, 'パスワード (確認用)' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
      <%= f.submit '登録', class: 'btn btn-secondary w-150px' %>
      <% end %>
    <p><%= link_to 'ログインの方はこちら', login_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="#" class="nav-link">投稿一覧</a></li>
      <li class="nav-item"><a href="#" class="nav-link">お気に入り一覧</a></li>
    </ul>
  </div>